*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 03/12/2003 at 12:52:28 by user CHARRISO
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWFLTOP.                          " Global Data
  INCLUDE LZWFLUXX.                          " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWFLF00                                . " subprograms
  INCLUDE LZWFLI00                                . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWFLF...                          " Subprograms
* INCLUDE LZWFLO...                          " PBO-Modules
* INCLUDE LZWFLI...                          " PAI-Modules
